// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/domain (interfaces: CatalogRepository,StockRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/repositories.go -package=mocks app/internal/domain CatalogRepository,StockRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "app/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCatalogRepository is a mock of CatalogRepository interface.
type MockCatalogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogRepositoryMockRecorder
	isgomock struct{}
}

// MockCatalogRepositoryMockRecorder is the mock recorder for MockCatalogRepository.
type MockCatalogRepositoryMockRecorder struct {
	mock *MockCatalogRepository
}

// NewMockCatalogRepository creates a new mock instance.
func NewMockCatalogRepository(ctrl *gomock.Controller) *MockCatalogRepository {
	mock := &MockCatalogRepository{ctrl: ctrl}
	mock.recorder = &MockCatalogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogRepository) EXPECT() *MockCatalogRepositoryMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockCatalogRepository) Search(ctx context.Context, q domain.SearchQuery) (domain.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, q)
	ret0, _ := ret[0].(domain.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockCatalogRepositoryMockRecorder) Search(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockCatalogRepository)(nil).Search), ctx, q)
}

// MockStockRepository is a mock of StockRepository interface.
type MockStockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStockRepositoryMockRecorder
	isgomock struct{}
}

// MockStockRepositoryMockRecorder is the mock recorder for MockStockRepository.
type MockStockRepositoryMockRecorder struct {
	mock *MockStockRepository
}

// NewMockStockRepository creates a new mock instance.
func NewMockStockRepository(ctrl *gomock.Controller) *MockStockRepository {
	mock := &MockStockRepository{ctrl: ctrl}
	mock.recorder = &MockStockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockRepository) EXPECT() *MockStockRepositoryMockRecorder {
	return m.recorder
}

// StockByStore mocks base method.
func (m *MockStockRepository) StockByStore(ctx context.Context, productID string, countryCache int) ([]domain.Province, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StockByStore", ctx, productID, countryCache)
	ret0, _ := ret[0].([]domain.Province)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StockByStore indicates an expected call of StockByStore.
func (mr *MockStockRepositoryMockRecorder) StockByStore(ctx, productID, countryCache any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StockByStore", reflect.TypeOf((*MockStockRepository)(nil).StockByStore), ctx, productID, countryCache)
}
